
//开始主页请求数据
export let START_FETCH_MAIN_PAGERDATA = "START_FETCH_MAIN_PAGERDATA";

//主页数据请求完成
export let COMPLETE_FETCH_MAIN_PAGERDATA = "COMPLETE_FETCH_MAIN_PAGERDATA";

//开始发现请求数据
export let START_FETCH_DISCOVER_PAGERDATA = "START_FETCH_DISCOVER_PAGERDATA";

//发现页数据请求完成
export let COMPLETE_FETCH_DISCOVER_PAGERDATA = "COMPLETE_FETCH_DISCOVER_PAGERDATA";

//开始少女漫画请求数据
export let START_FETCH_GIRL_PAGERDATA = "START_FETCH_GIRL_PAGERDATA";

//少女漫画页数据请求完成
export let COMPLETE_FETCH_GIRL_PAGERDATA = "COMPLETE_FETCH_GIRL_PAGERDATA";

//开始耽美漫画请求数据
export let START_FETCH_TANBI_PAGERDATA = "START_FETCH_TANBI_PAGERDATA";

//耽美漫画页数据请求完成
export let COMPLETE_FETCH_TANBI_PAGERDATA = "COMPLETE_FETCH_TANBI_PAGERDATA";


//开始ChaPtePage请求数据
export let START_FETCH_CHAPTER_PAGERDATA = "START_FETCH_CHAPTER_PAGERDATA";

//ChaPtePage页数据请求完成
export let COMPLETE_FETCH_CHAPTER_PAGERDATA = "COMPLETE_FETCH_CHAPTER_PAGERDATA";

//DetailPage
export let START_FETCH_DETAIL_PAGERDATA = "START_FETCH_DETAIL_PAGERDATA";

export let COMPLETE_FETCH_DETAIL_PAGERDATA = "COMPLETE_FETCH_DETAIL_PAGERDATA";


